brain_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('todos/', include('todos.urls')),
]

todos/urls.py
from django.urls import path

from todos.views import (
    TodoListView, 
    TodoListDetail,
    TodoListCreate,
    TodoListUpdate,
    TodoListDelete,
)

from todos.views import TodoItemCreate, TodoItemUpdate

urlpatterns = [

    path("", TodoListView.as_view(), name='todo_list_list'),
    path('<int:pk>/', TodoListDetail.as_view(), name='todo_list_detail'),
    path('create/', TodoListCreate.as_view(), name='todo_list_create'),
    path('<int:pk>/edit/', TodoListUpdate.as_view(), name='todo_list_update'),
    path('<int:pk>/delete/', TodoListDelete.as_view(), name='todo_list_delete'),
    ####   end of todo list paths ####

    path('items/create/', TodoItemCreate.as_view(), name='todo_item_create'),
    path('items/<int:pk>/edit/', TodoItemUpdate.as_view(), name='todo_item_update'),
]

todos/models.py
from django.db import models
from django.forms import CharField

# Create your models here.

class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey("TodoList", related_name="items", on_delete=models.CASCADE)

    def __str__(self):
        return self.task

todos/views.py
from django.shortcuts import render
from todos.models import TodoList, TodoItem
from django.urls import reverse, reverse_lazy

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

# Create your views here.

class TodoListView(ListView):
    model = TodoList
    template_name = "todos/list.html"

class TodoListDetail(DetailView):
    model = TodoList
    template_name = 'todos/detail.html'

class TodoListCreate(CreateView):
    model = TodoList
    template_name = 'todos/create.html'
    fields = ['name']
    
    def get_success_url(self): # look into get success url
        return reverse_lazy('todo_list_detail', kwargs={'pk': self.object.id})
    

class TodoListUpdate(UpdateView):
    model = TodoList
    template_name = 'todos/edit.html'
    fields = ['name']

    def get_success_url(self):
        return reverse_lazy('todo_list_detail', kwargs={'pk': self.object.id})

class TodoListDelete(DeleteView):
    model = TodoList
    template_name = 'todos/delete.html'
    success_url = reverse_lazy('todo_list_list')

class TodoItemCreate(CreateView):
    model = TodoItem
    template_name = 'todoitem/create.html'
    fields = ['task', 'due_date', 'is_completed', 'list']

    def get_success_url(self):
        return reverse_lazy('todo_list_detail', kwargs={'pk': self.object.list.id})

class TodoItemUpdate(UpdateView):
    model = TodoItem
    template_name = 'todoitem/edit.html'
    fields = ['task', 'due_date', 'is_completed', 'list'] 

    def get_success_url(self):
        return reverse_lazy('todo_list_detail', kwargs={'pk': self.object.list.id})

todos/templates/todoitem/create.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
</head>

<body>
  <header>
    <nav>
    </nav>
  </header>
  <main>
    <div>
        <h1>Create a new item</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Create</button>
      </div>
    </form>
    </div>
  </main>
 
</body>

</html>

todos/templates/todoitem/edit.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
</head>

<body>
  <header>
    <nav>
    </nav>
  </header>
  <main>
    <div>
        <h1>Update item</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Update</button>
      </div>
    </form>
    </div>
  </main>
</body>

</html>

todos/templates/todos/create.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
</head>

<body>
  <header>
    <nav>
    </nav>
  </header>
  <main>
    <div>
        <h1>Create a new list</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Create</button>
      </div>
    </form>
    </div>
  </main>
 
</body>

</html>

todos/templates/todos/delete.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
</head>

<body>
  <header>
    <nav>
    </nav>
  </header>
  <main>
    <div>
    <h1>Are you sure?</h1>
    <form method="post">
        {% csrf_token %}
        
        {{ form }}
        <button class="button">Delete</button> 
    </form>
    </div>
  </main>
</body>

</html>

todos/templates/todos/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
</head>

<body>
  <header>
    <nav>
    </nav>
  </header>
  <main>
    <div>
        <h1>{{ todolist.name }}</h1>
        <div>
          <a href="{% url 'todo_list_update' todolist.id %}">Edit</a>
          <p>
          <a href="{% url 'todo_list_delete' todolist.id %}">Delete</a>
          </p>
        </div>
        <h2>Tasks</h2>
        <table>
            <thead>
                <tr>
                    <th>Task</th>

                    <th>Due Date</th>
                </tr>
            </thead>
            <tbody>
                {% for task in todolist.items.all %}
                <tr>
                    <td><a href="{% url 'todo_item_update' task.id %}">{{ task.task }}</a></td>
                    <td>{{ task.due_date }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
  </main>
</body>

</html>

todos/templates/todos/edit.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
</head>

<body>
  <header>
    <nav>
    </nav>
  </header>
  <main>
    <div>
        <h1>Update list</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Update</button>
      </div>
    </form>
    </div>
  </main>
</body>

</html>

todos/templates/todos/list.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
</head>

<body>
  <header>
    <nav>
    </nav>
  </header>
  <main>
    <div>
        <h1>My Lists</h1>
        <div>
          <p>
            <a href="{% url 'todo_list_create' %}">Create a new list</a>
            <p>
            <a href="{% url 'todo_item_create' %}">Create a new item</a>
            </p>
          </p>
        </div>
        <table>
           <thead>
            <tr>
                <th>Name</th>
                <th>Number of items</th>
            </tr>
           </thead>
           <tbody>
            {% for list in todolist_list %}
            <tr>

                <td><a href="{% url 'todo_list_detail' list.pk %}">{{ list.name }}</a></td>
                <td>{{ list.items.all|length }}</td>
            </tr>
            {% endfor %}
           </tbody>
        </table>
    </div>
  </main>
</body>

</html>